-- ============================================================
-- MOVE — Phase Hooks
-- ============================================================
function before_move(phaseName, phase)
    if DICE_CONTEST and DICE_CONTEST.winner then
        UI.setAttribute("iconWinnerArmy"..DICE_CONTEST.winner, "active", "false")
    end
    if TURN.phase ~= phaseName then resetTurnForPhase() end
    TURN.phase = phaseName
end

function after_move(phaseName, phase)
end
